arch:
  - amd64

services:
  - docker

env:
  global:
    - DOCKER_REPO="piwi3910/hello-multiarch"
    - GIT_SHA="$(git rev-parse --short HEAD)"

script:
  - docker build --pull --tag "${DOCKER_REPO}:${GIT_SHA}" .
  - docker run "${DOCKER_REPO}:${GIT_SHA}"
  - docker tag "${DOCKER_REPO}:${GIT_SHA}" "${DOCKER_REPO}:travis"
  - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin &> /dev/null
  - docker push "${DOCKER_REPO}:travis"
