arch:
  - amd64
os:
  - linux

language: ruby
dist: xenial

services:
  - docker

env:
  global:
    - DOCKER_REPO="piwi3910/hello-multiarch"
    - GIT_SHA="$(git rev-parse --short HEAD)"

jobs:
  include:
    - stage: Build
      script:
        - docker build --pull --tag "${DOCKER_REPO}:${GIT_SHA}" .
        - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin &> /dev/null
        - docker tag "${DOCKER_REPO}:${GIT_SHA}" "${DOCKER_REPO}:testing"
        - docker push "${DOCKER_REPO}:testing"

    - stage: Testing
      script:
        - docker pull "${DOCKER_REPO}:testing"
        - docker run "${DOCKER_REPO}:testing"

    - stage: Publish
      script:
        - docker pull "${DOCKER_REPO}:testing"
        - docker tag "${DOCKER_REPO}:testing" "${DOCKER_REPO}:latest"
        - docker push "${DOCKER_REPO}:latest"
