sudo: required
dist: focal
services:
  - docker

env:
  - IMAGE_NAME=piwi3910/hello-multiarch
  - DOCKER_CLI_EXPERIMENTAL=enabled

install: []
before_script:
  - apt install qemu binfmt-support qemu-user-static -y
  - update-binfmts --display
  - docker buildx create --name mybuilder --platform linux/arm,linux/arm64,linux/amd64
  - docker buildx use mybuilder
  - docker buildx inspect --bootstrap
script:
  - docker buildx build --pull --tag "$IMAGE_NAME" .

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - git_sha="$(git rev-parse --short HEAD)"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${git_sha}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${git_sha}"
  on:
    branch: master